### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by elegaanz** [sgrif/swirl#15]
Hello! I would just like to know if you plan to support SQlite at some point? This crate looks really nice and I would like to use it, but my project should support both PostgreSQL and SQlite.

Thanks!

**Comment by sgrif** [comment]
No, SQLite support isn't something that is planned. Swirl specifically uses row locking features only present in PostgreSQL in order to work. It's certainly possible to have a more general implementation like `delayed_job` in Ruby, but that would be a fundamentally different project than this is trying to be
